import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await currentUser();

    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <div className=" overflow-x-hidden">
                        <Header user={JSON.parse(JSON.stringify(user))} />
                        {children}
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
