import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { fetchProfile } from "@/actions/onboard";
import { UserProfileType } from "./onboard/Components/Onboard";
import { RecruiterFormType } from "./onboard/Components/Forms/RecruiterForm";
import { CandidateFormType } from "./onboard/Components/Forms/CanditateForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await currentUser();
    let profile;

    if (user) {
        profile = await fetchProfile(user?.id);
    }

    return (
        <ClerkProvider>
            <html lang="en" data-theme="light">
                <body className={inter.className}>
                    <div className=" overflow-x-hidden">
                        <Header
                            user={JSON.parse(JSON.stringify(user))}
                            profile={profile}
                        />
                        {children}
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
